"""Assemble the ``@dhague/wiki-knowledge`` npm package at release time (#327).

Build-time half of the npm-deployer distribution (ADR-0018 / #218): this
script assembles the OpenCode package's full payload into
``wiki-plugin/opencode-npm/`` from the canonical Claude Code sources. It runs
at release time (from ``scripts/release.sh``); ``npm publish`` is a separate
human step.

What it produces, from the canonical sources:

- ``agents/*.md`` + ``commands/*.md`` — regenerated by ``generate-opencode.py``
  (invoked as a subprocess, exactly like install-opencode.py), using the
  package's own ``templates/model-config.json`` so the shipped agents carry
  the same model mapping that deploys.
- ``skills/<six skill dirs>/`` — copied from ``skills/``.
- ``plugins/session-tracker.ts`` + ``plugins/wiki-enchiridion.ts`` — copied
  from ``wiring/opencode/plugins/``.
- ``wiki-knowledge/cli.cjs`` + ``wiki-knowledge/node-sqlite3-wasm.wasm`` —
  the ADR-0017 bundled runtime, copied from ``scripts/`` (release.sh has
  already refreshed them from a fresh build).
- ``templates/config.json`` — the ``plugin_root`` marker placeholder the
  deployer fills at install time (the shape install-opencode.py writes).
- ``templates/model-config.json`` — the default model mapping, derived from
  ``generate-opencode.py --default-models`` (its DEFAULT_MODELS is the single
  source for the mapping).
- ``templates/opencode-deps.json`` — the ``@opencode-ai/plugin`` runtime
  dependency version, read from ``wiring/opencode/package.json`` (the single
  source); deploy.js merges this into ``<target>/package.json`` so OpenCode's
  startup ``bun install`` picks up the dependency.
- ``package.json`` ``version`` — written from ``.claude-plugin/plugin.json``
  (the single source for the version; one cut-release bumps both).

The generated content (agents/, commands/, skills/, plugins/,
wiki-knowledge/) is gitignored — it is regenerated on every release, never
edited by hand. ``package.json``, ``templates/``, and ``.gitignore`` are the
committed durable source (``templates/opencode-deps.json`` is committed and
refreshed by this script on every release).

CLI::

    python assemble-opencode-package.py [--plugin-root DIR] [--output DIR]
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

#: The six skill dirs, plugin-relative — mirrors generate-opencode.py's
#: SKILLS tuple; keep in sync.
SKILLS = (
    "wiki-conventions",
    "wiki-ingest",
    "wiki-init",
    "wiki-retrieval",
    "wiki-watch",
    "save-conversation",
)

#: The marker shape install-opencode.py writes to
#: ``<target>/wiki-knowledge/config.json`` — the deployer (#328) fills
#: ``plugin_root`` at install time.
MARKER = {"plugin_root": "<filled at deploy time>"}


class AssemblyError(RuntimeError):
    """Raised when the package can't be assembled (missing canonical source,
    generation failure, …)."""


def _read_text(path: Path, what: str) -> str:
    if not path.is_file():
        raise AssemblyError(f"{what} not found: {path}")
    return path.read_text(encoding="utf-8")


def read_plugin_version(plugin_root: Path | str) -> str:
    """The version from ``.claude-plugin/plugin.json`` — the single source."""
    path = Path(plugin_root) / ".claude-plugin" / "plugin.json"
    data = json.loads(_read_text(path, "plugin.json"))
    version = data.get("version")
    if not version:
        raise AssemblyError(f"plugin.json at {path} carries no version")
    return version


def write_package_version(package_dir: Path | str, version: str) -> Path:
    """Set ``version`` on the committed ``package.json`` in place, preserving
    every other field and the file's formatting. Returns the file path."""
    path = Path(package_dir) / "package.json"
    data = json.loads(_read_text(path, "package.json"))
    data["version"] = version
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return path


def fetch_default_models(plugin_root: Path | str) -> dict:
    """The default model mapping, from ``generate-opencode.py --default-models``
    — DEFAULT_MODELS there is the single source of truth for which canonical
    model names exist and their provider/model-id defaults."""
    root = Path(plugin_root)
    proc = subprocess.run(
        [
            sys.executable,
            str(root / "scripts" / "generate-opencode.py"),
            "--default-models",
            "--plugin-root",
            str(root),
        ],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise AssemblyError(
            f"generate-opencode.py --default-models failed ({proc.returncode}): "
            f"{proc.stderr.strip()}"
        )
    try:
        data = json.loads(proc.stdout.strip())
    except json.JSONDecodeError as exc:
        raise AssemblyError(
            f"generate-opencode.py --default-models returned invalid JSON: {exc}"
        ) from exc
    if not isinstance(data, dict):
        raise AssemblyError("generate-opencode.py --default-models returned a non-object")
    return data


def write_config_templates(package_dir: Path | str, model_map: dict) -> list[Path]:
    """Write/refresh the two config templates the deployer ships: the marker
    (``plugin_root`` placeholder) and the default model mapping. The model
    mapping is derived from generate-opencode.py, so a committed template can
    never drift from the generators' defaults."""
    out = Path(package_dir)
    templates = out / "templates"
    templates.mkdir(parents=True, exist_ok=True)
    marker_path = templates / "config.json"
    marker_path.write_text(json.dumps(MARKER, indent=2) + "\n", encoding="utf-8")
    models_path = templates / "model-config.json"
    models_path.write_text(json.dumps(model_map, indent=2) + "\n", encoding="utf-8")
    return [marker_path, models_path]


def read_opencode_plugin_version(plugin_root: Path | str) -> str:
    """The ``@opencode-ai/plugin`` version from ``wiring/opencode/package.json``
    devDependencies — the single source of truth. deploy.js needs this to write
    the runtime dependency into the target's package.json."""
    path = Path(plugin_root) / "wiring" / "opencode" / "package.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise AssemblyError(
            f"wiring/opencode/package.json is not readable or not valid JSON: {exc}"
        ) from exc
    if not isinstance(data, dict):
        raise AssemblyError("wiring/opencode/package.json must be a JSON object")
    version = data.get("devDependencies", {}).get("@opencode-ai/plugin")
    if not version:
        raise AssemblyError(
            "wiring/opencode/package.json has no devDependencies['@opencode-ai/plugin']"
        )
    return version


def write_opencode_deps(package_dir: Path | str, version: str) -> Path:
    """Write ``templates/opencode-deps.json`` carrying the ``@opencode-ai/plugin``
    version that deploy.js merges into ``<target>/package.json`` at install time.
    This is the single committed record of the runtime dependency version."""
    out = Path(package_dir)
    templates = out / "templates"
    templates.mkdir(parents=True, exist_ok=True)
    deps_path = templates / "opencode-deps.json"
    deps_path.write_text(
        json.dumps({"@opencode-ai/plugin": version}, indent=2) + "\n",
        encoding="utf-8",
    )
    return deps_path


def copy_skills(plugin_root: Path | str, package_dir: Path | str) -> list[Path]:
    """Copy the six skill dirs into the package, replacing the whole skills/
    tree so a skill renamed/removed upstream can't leave a stale copy."""
    root = Path(plugin_root)
    out = Path(package_dir) / "skills"
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)
    written: list[Path] = []
    for skill in SKILLS:
        src = root / "skills" / skill
        if not (src / "SKILL.md").is_file():
            raise AssemblyError(f"skill {skill!r} has no SKILL.md under {src}")
        dst = out / skill
        shutil.copytree(src, dst)
        written.append(dst)
    return written


def copy_session_tracker(plugin_root: Path | str, package_dir: Path | str) -> Path:
    """Copy the OpenCode session-tracker plugin into the package's plugins/."""
    root = Path(plugin_root)
    src = root / "wiring" / "opencode" / "plugins" / "session-tracker.ts"
    _read_text(src, "session-tracker.ts")
    dst = Path(package_dir) / "plugins" / "session-tracker.ts"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return dst


def copy_wiki_enchiridion(plugin_root: Path | str, package_dir: Path | str) -> Path:
    """Copy the wiki-enchiridion OpenCode plugin into the package's plugins/.

    This plugin exposes the script layer as an in-process ``wiki`` tool so
    OpenCode sessions can call enchiridion subcommands without ``node`` on PATH.
    deploy.js ships and deploys it alongside session-tracker.ts.
    """
    root = Path(plugin_root)
    src = root / "wiring" / "opencode" / "plugins" / "wiki-enchiridion.ts"
    _read_text(src, "wiki-enchiridion.ts")
    dst = Path(package_dir) / "plugins" / "wiki-enchiridion.ts"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return dst


def copy_runtime(plugin_root: Path | str, package_dir: Path | str) -> list[Path]:
    """Copy the ADR-0017 bundled runtime (cli.cjs + wasm) into the package."""
    root = Path(plugin_root)
    out = Path(package_dir) / "wiki-knowledge"
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename in ("cli.cjs", "node-sqlite3-wasm.wasm"):
        src = root / "scripts" / filename
        if not src.is_file():
            raise AssemblyError(f"bundled runtime {filename} not found: {src}")
        dst = out / filename
        shutil.copy2(src, dst)
        written.append(dst)
    return written


def _run_generate(argv: list[str]) -> None:
    """Run generate-opencode.py (full argv incl. interpreter + script path);
    raise :class:`AssemblyError` on a non-zero exit."""
    proc = subprocess.run(argv, capture_output=True, text=True)
    if proc.returncode != 0:
        raise AssemblyError(
            f"generate-opencode.py failed ({proc.returncode}): {proc.stderr.strip()}"
        )


def assemble(
    plugin_root: Path | str,
    package_dir: Path | str,
    *,
    run_generate=_run_generate,
) -> list[Path]:
    """Assemble the full npm package payload into ``package_dir``.

    Idempotent: every generated/copied path is overwritten in place, and a
    second run writes identical bytes (agents/commands generation is
    deterministic). Returns the paths written, newest-first ordering across
    the pipeline.

    The canonical sources are validated up front (generation runs first, so a
    generation failure aborts before any copy happens); each step raises
    :class:`AssemblyError` rather than silently skipping a missing source.
    """
    root = Path(plugin_root)
    out = Path(package_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Clear every generated subdir so a re-run never leaves stale content
    # behind (a skill renamed upstream, a regenerated agent, …). The committed
    # package.json and templates/ are never touched here.
    for subdir in ("agents", "commands", "skills", "plugins", "wiki-knowledge"):
        stale = out / subdir
        if stale.exists():
            shutil.rmtree(stale)

    version = read_plugin_version(root)

    written: list[Path] = []
    written.append(write_package_version(out, version))

    model_map = fetch_default_models(root)
    written.extend(write_config_templates(out, model_map))

    opencode_plugin_version = read_opencode_plugin_version(root)
    written.append(write_opencode_deps(out, opencode_plugin_version))

    generate_argv = [
        sys.executable,
        str(root / "scripts" / "generate-opencode.py"),
        "--plugin-root", str(root),
        "--model-config", str(out / "templates" / "model-config.json"),
        "--output", str(out),
    ]
    run_generate(generate_argv)

    written.extend(copy_skills(root, out))
    written.append(copy_session_tracker(root, out))
    written.append(copy_wiki_enchiridion(root, out))
    written.extend(copy_runtime(root, out))

    return written


def main(argv: list[str] | None = None) -> int:  # pragma: no cover - thin CLI
    parser = argparse.ArgumentParser(
        description="Assemble the @dhague/wiki-knowledge npm package from the "
        "canonical plugin sources.",
    )
    parser.add_argument(
        "--plugin-root",
        default=str(Path(__file__).resolve().parent.parent),
        help="the plugin's install directory (defaults to this script's own "
        "plugin, so a bare run assembles the package from the plugin source)",
    )
    parser.add_argument(
        "--output", default=None,
        help="the package directory to assemble into (defaults to "
        "<plugin-root>/opencode-npm)",
    )
    args = parser.parse_args(argv)

    root = Path(args.plugin_root)
    package_dir = Path(args.output) if args.output else root / "opencode-npm"

    try:
        written = assemble(root, package_dir)
    except AssemblyError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    for path in written:
        print(path)
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())