"""Regenerate ``wiki/_index.md`` from every page's frontmatter under ``wiki/**``.

Derived data — always regenerated, never hand-edited or trusted as a cache.
Indexes ``wiki/**`` only; ``raw/`` is never walked or listed.

Each page becomes one row of a GFM table: path, title, summary, tags,
source_date, volatility, and its outgoing edges (``raw_source``,
``supersedes``, and the five typed-edge keys). Per the amended frontmatter
contract (19be866), each of those holds quoted markdown links rather than a
flat ``links:`` list, so recovering a target means stripping the markdown —
reusing ``wikipage.iter_links``, which already parses this shape — and then
re-basing the path from the *page's* directory to be relative to ``wiki/``
(the directory ``_index.md`` itself lives in), since a flat index can't
otherwise say what a page-relative link resolves to.

CLI::

    python build_index.py   # regenerates wiki/_index.md for the resolved vault
"""
from __future__ import annotations

import posixpath
import sys
from dataclasses import dataclass, field
from pathlib import Path

import wikipage

#: Order mirrors the frontmatter schema block in the conventions spec.
_EDGE_KEYS = (
    "raw_source",
    "supersedes",
    "refines",
    "contradicts",
    "example-of",
    "source",
    "related",
)

_HEADER = (
    "<!-- Generated by build_index.py — do not edit by hand. "
    "Indexes wiki/** only, never raw/. -->\n"
    "\n"
    "| Path | Title | Summary | Tags | Source date | Volatility | Edges |\n"
    "| --- | --- | --- | --- | --- | --- | --- |\n"
)


@dataclass(frozen=True)
class PageRecord:
    """One page's index row, already reduced to plain rendering values."""

    rel: str
    title: str
    summary: str
    tags: list[str]
    source_date: str
    volatility: str
    edges: list[tuple[str, list[str]]] = field(default_factory=list)


def _link_target(markdown_link: str) -> str:
    """Strip a quoted markdown link (``[title](path)``) down to its path."""
    match = next(iter(wikipage.iter_links(markdown_link)), None)
    if match is None:
        raise ValueError(f"not a markdown link: {markdown_link!r}")
    return match.dest


def _rebase_to_wiki_root(target: str, page_dir: str) -> str:
    """Re-express a target relative to the page's own directory as relative to wiki/."""
    return posixpath.normpath(posixpath.join(page_dir, target))


def _page_record(rel: str, text: str) -> PageRecord:
    data = wikipage.WikiPage(text).frontmatter or {}
    page_dir = posixpath.dirname(rel)

    edges: list[tuple[str, list[str]]] = []
    for key in _EDGE_KEYS:
        value = data.get(key)
        if not value:
            continue
        if key == "raw_source":
            targets = [_rebase_to_wiki_root(_link_target(value), page_dir)]
        else:
            targets = [
                _rebase_to_wiki_root(_link_target(item), page_dir) for item in value
            ]
        edges.append((key, targets))

    return PageRecord(
        rel=rel,
        title=str(data.get("title", "")),
        summary=str(data.get("summary", "")),
        tags=list(data.get("tags") or []),
        source_date=str(data.get("source_date", "")),
        volatility=str(data.get("volatility", "")),
        edges=edges,
    )


def _cell(text: str) -> str:
    """Sanitize a value for a single GFM table cell: no pipes, no newlines."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _render_row(rec: PageRecord) -> str:
    tags_cell = "[" + ", ".join(rec.tags) + "]"
    edges_cell = "; ".join(
        f"{key}:{','.join(targets)}" for key, targets in rec.edges
    )
    link = f"[{rec.rel}]({rec.rel})"
    cells = [
        link,
        rec.title,
        rec.summary,
        tags_cell,
        rec.source_date,
        rec.volatility,
        edges_cell,
    ]
    return "| " + " | ".join(_cell(c) for c in cells) + " |"


def build_index(pages: dict[str, str]) -> str:
    """Pure: render ``_index.md`` content from ``{rel: text}`` (rel relative to wiki/).

    ``_index.md`` itself, if present in ``pages``, is skipped so a stale copy
    never leaks into its own regeneration.
    """
    rows = [
        _render_row(_page_record(rel, text))
        for rel, text in sorted(pages.items())
        if rel != "_index.md"
    ]
    return _HEADER + "\n".join(rows) + ("\n" if rows else "")


def write_index(vault_root: Path | str) -> Path:
    """Walk the on-disk vault's ``wiki/**`` and (re)write ``wiki/_index.md``."""
    wiki_root = Path(vault_root) / "wiki"
    pages: dict[str, str] = {}
    for path in wiki_root.rglob("*.md"):
        rel = path.relative_to(wiki_root).as_posix()
        if rel == "_index.md":
            continue
        pages[rel] = path.read_text(encoding="utf-8")

    index_path = wiki_root / "_index.md"
    index_path.write_text(build_index(pages), encoding="utf-8")
    return index_path


def _main(argv=None) -> int:  # pragma: no cover - thin CLI wrapper
    import vault

    root = vault.resolve_vault_root()
    path = write_index(root)
    print(path)
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(_main())
