"""Regenerate ``wiki/_index.md`` from every page's frontmatter under ``wiki/**``.

Derived data — always regenerated, never hand-edited or trusted as a cache.
Indexes ``wiki/**`` only; ``raw/`` is never walked or listed.

Each page becomes one row of a GFM table: path, title, summary, tags,
source_date, volatility, and its outgoing edges (``raw_source``,
``supersedes``, and the five typed-edge keys). Each of those holds quoted
markdown links rather than a flat ``links:`` list, so recovering a target
means stripping the markdown — reusing ``wikipage.iter_links``, which
already parses this shape — and then re-basing the path from the *page's*
directory to be relative to ``wiki/`` (the directory ``_index.md`` itself
lives in), since a flat index can't otherwise say what a page-relative
link resolves to.

CLI::

    python build_index.py   # regenerates wiki/_index.md for the resolved vault
"""
from __future__ import annotations

import sys
from pathlib import Path

from page_record import PageRecord, load_records
from vault import Vault

_HEADER = (
    "<!-- Generated by build_index.py — do not edit by hand. "
    "Indexes wiki/** only, never raw/. -->\n"
    "\n"
    "| Path | Title | Summary | Tags | Source date | Volatility | Edges |\n"
    "| --- | --- | --- | --- | --- | --- | --- |\n"
)


def _cell(text: str) -> str:
    """Sanitize a value for a single GFM table cell: no pipes, no newlines."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _render_row(rec: PageRecord) -> str:
    tags_cell = "[" + ", ".join(rec.tags) + "]"
    edges_cell = "; ".join(
        f"{key}:{','.join(targets)}" for key, targets in rec.edges
    )
    link = f"[{rec.rel}]({rec.rel})"
    cells = [
        link,
        rec.title,
        rec.summary,
        tags_cell,
        rec.source_date,
        rec.volatility,
        edges_cell,
    ]
    return "| " + " | ".join(_cell(c) for c in cells) + " |"


def build_index(pages: dict[str, str]) -> str:
    """Pure: render ``_index.md`` content from ``{rel: text}`` (rel relative to wiki/).

    ``_index.md`` itself, if present in ``pages``, is skipped so a stale copy
    never leaks into its own regeneration.
    """
    records = load_records(pages)
    rows = [_render_row(records[rel]) for rel in sorted(records)]
    return _HEADER + "\n".join(rows) + ("\n" if rows else "")


def write_index(vault_root: Path | str) -> Path:
    """(Re)write ``wiki/_index.md`` from the on-disk vault's pages.

    Enumeration is Vault's job: pages come from
    ``Vault.load_wiki_pages()`` (vault-relative ``rel``, never ``raw/``).
    This function only rebases each ``rel`` back to wiki/-relative — since
    ``_index.md`` itself lives in ``wiki/`` — before handing off to
    :func:`build_index`, which excludes ``_index.md`` from the render.
    """
    wiki_root = Path(vault_root) / "wiki"
    pages = {
        rel.removeprefix("wiki/"): text
        for rel, text in Vault(vault_root).load_wiki_pages().items()
    }

    index_path = wiki_root / "_index.md"
    index_path.write_text(build_index(pages), encoding="utf-8")
    return index_path


def _main(argv=None) -> int:  # pragma: no cover - thin CLI wrapper
    import vault

    root = vault.resolve_vault_root()
    path = write_index(root)
    print(path)
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(_main())
