"""TDD for init_wiki.py — scaffolding a brand-new vault.

Covers the mechanical half (folders, empty index, git repo, .gitignore,
settings.json) that used to live as prose in wiki-init/SKILL.md; deployment
mode is still a caller-supplied judgment call, not inferred here.
"""
import json
import subprocess

import pytest

import init_wiki


@pytest.fixture(autouse=True)
def _git_identity(monkeypatch):
    # init_wiki() both `git init`s and commits within one call, so there's no
    # window to `git config` a fresh repo in between — set identity and
    # disable gpg-signing via env instead, regardless of the host's global config.
    monkeypatch.setenv("GIT_AUTHOR_NAME", "Test")
    monkeypatch.setenv("GIT_AUTHOR_EMAIL", "test@example.com")
    monkeypatch.setenv("GIT_COMMITTER_NAME", "Test")
    monkeypatch.setenv("GIT_COMMITTER_EMAIL", "test@example.com")
    monkeypatch.setenv("GIT_CONFIG_COUNT", "1")
    monkeypatch.setenv("GIT_CONFIG_KEY_0", "commit.gpgsign")
    monkeypatch.setenv("GIT_CONFIG_VALUE_0", "false")


def _git(root, *args):
    return subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, check=True
    )


# --- is_vault ----------------------------------------------------------

def test_is_vault_false_for_empty_dir(tmp_path):
    assert init_wiki.is_vault(tmp_path) is False


def test_is_vault_true_when_wiki_dir_present(tmp_path):
    (tmp_path / "wiki").mkdir()
    assert init_wiki.is_vault(tmp_path) is True


def test_is_vault_true_when_marker_file_present(tmp_path):
    (tmp_path / ".wiki-root").touch()
    assert init_wiki.is_vault(tmp_path) is True


# --- init_wiki: refusal --------------------------------------------------

def test_refuses_to_scaffold_existing_vault(tmp_path):
    (tmp_path / "wiki").mkdir()
    with pytest.raises(init_wiki.InitError, match="already looks like a vault"):
        init_wiki.init_wiki(tmp_path, mode="dedicated")


def test_rejects_unknown_mode(tmp_path):
    with pytest.raises(init_wiki.InitError, match="unknown mode"):
        init_wiki.init_wiki(tmp_path, mode="bogus")


def test_query_from_anywhere_requires_plugin_root(tmp_path):
    with pytest.raises(init_wiki.InitError, match="plugin_root"):
        init_wiki.init_wiki(tmp_path, mode="query-from-anywhere")


# --- init_wiki: dedicated mode -------------------------------------------

def test_dedicated_mode_creates_kind_folders(tmp_path):
    init_wiki.init_wiki(tmp_path, mode="dedicated")
    for kind in init_wiki.KIND_FOLDERS:
        assert (tmp_path / "wiki" / kind).is_dir()
    assert (tmp_path / "raw").is_dir()


def test_dedicated_mode_writes_empty_index(tmp_path):
    index_path = init_wiki.init_wiki(tmp_path, mode="dedicated")
    assert index_path == tmp_path / "wiki" / "_index.md"
    assert "Generated by build_index.py" in index_path.read_text(encoding="utf-8")


def test_dedicated_mode_writes_gitignore(tmp_path):
    init_wiki.init_wiki(tmp_path, mode="dedicated")
    gitignore = (tmp_path / ".gitignore").read_text(encoding="utf-8")
    assert "*.rsls" in gitignore
    assert ".claude/wiki-knowledge/sessions/" in gitignore
    assert ".wiki-knowledge/" in gitignore  # search index per ADR-0006


def test_dedicated_mode_writes_no_settings_json(tmp_path):
    init_wiki.init_wiki(tmp_path, mode="dedicated")
    assert not (tmp_path / ".claude" / "settings.json").exists()


def test_dedicated_mode_initializes_git_repo_with_commit(tmp_path):
    init_wiki.init_wiki(tmp_path, mode="dedicated")
    assert (tmp_path / ".git").is_dir()
    log = _git(tmp_path, "log", "--oneline").stdout
    assert "Initialize wiki vault" in log


def test_dedicated_mode_reuses_existing_git_repo(tmp_path):
    _git(tmp_path, "init")
    init_wiki.init_wiki(tmp_path, mode="dedicated")
    # only one commit — init_wiki did not re-init or produce an extra commit
    log = _git(tmp_path, "log", "--oneline").stdout.strip().splitlines()
    assert len(log) == 1


# --- init_wiki: query-from-anywhere mode ---------------------------------

def test_query_from_anywhere_writes_settings_json(tmp_path):
    init_wiki.init_wiki(tmp_path, mode="query-from-anywhere", plugin_root="/plugin/root")
    settings = json.loads((tmp_path / ".claude" / "settings.json").read_text(encoding="utf-8"))
    marketplace = settings["extraKnownMarketplaces"]["wiki-knowledge-plugin"]
    assert marketplace["source"] == {"source": "directory", "path": "/plugin/root"}
    assert settings["enabledPlugins"] == {"wiki-knowledge@wiki-knowledge-plugin": True}


def test_query_from_anywhere_commits_settings_json(tmp_path):
    init_wiki.init_wiki(tmp_path, mode="query-from-anywhere", plugin_root="/plugin/root")
    show = _git(tmp_path, "show", "--stat", "HEAD").stdout
    assert ".claude/settings.json" in show
